blank_issues_enabled: true
contact_links:
  - name: 📋 Backlog e Quadro Kanban
    url: https://github.com/users/Goguel/projects/2
    about: Consulte o quadro Kanban oficial do SmOrg com o status das Sprints
